version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-assets
    ports:
      - "5030:5432"
    environment:
      POSTGRES_DB: asset_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - pg_assets_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: backend-assets
    ports:
      - "3030:3030"
    environment:
      DB_USER: postgres
      DB_HOST: postgres
      DB_NAME: asset_management
      DB_PASSWORD: admin123
      DB_PORT: 5432
    depends_on:
      - postgres

  employee-assets:
    build: ./Employee-Assets
    container_name: employee-assets
    ports:
      - "8039:80"
    depends_on:
      - backend

  hr-assets:
    build: ./HR-Assets
    container_name: hr-assets
    ports:
      - "8040:80"
    depends_on:
      - backend

volumes:
  pg_assets_data:

